#!/bin/bash
destination_dir="/tmp/u"

# Create the destination directory if it doesn't exist
mkdir -p "$destination_dir"

# Move files starting with an uppercase letter to the destination directory
for file in [A-Z]*; do
    if [ -f "$file" ]; then
            mv "$file" "$destination_dir"
	            echo "Moved $file to $destination_dir"
		        fi
			done

