#!/bin/bash
parent_dir="$(dirname "$(pwd)")"
html_files="$(find . -maxdepth 1 -type f -name '*.html')"

for file in $html_files; do
    base_file="$(basename "$file")"
        destination="$parent_dir/$base_file"
	    if [ ! -e "$destination" ] || [ "$file" -nt "$destination" ]; then
	            cp "$file" "$destination"
		            echo "Copied $file to $destination"
			        fi
				done

